server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    host: 192.168.0.147
    username: leyou
    password: leyou
  redis:
    host: 192.168.0.147
